# Generated by Django 2.2 on 2019-05-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('coordinate', models.CharField(max_length=50)),
                ('descript', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('toilet', 'Toilet'), ('parking', 'Parking'), ('falculty', 'Falculty'), ('cafeteria', 'Cafeteria'), ('other', 'Other')], default='other', max_length=50)),
                ('img_path', models.CharField(max_length=255)),
            ],
        ),
    ]
