# Generated by Django 2.2 on 2019-05-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='type',
            new_name='location_type',
        ),
    ]
