# Generated by Django 2.2 on 2019-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190505_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zone_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
