# Generated by Django 2.2 on 2019-05-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_location_zone_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('toilet', 'Toilet'), ('parking', 'Parking'), ('faculty', 'Faculty'), ('cafeteria', 'Cafeteria'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
