# Generated by Django 2.2 on 2019-05-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20190506_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='leo', max_length=50),
            preserve_default=False,
        ),
    ]
