# Generated by Django 2.2 on 2019-05-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_map_request_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('Subject_type', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
