# Generated by Django 2.2 on 2019-05-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20190524_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Subject_type',
        ),
    ]
