# Generated by Django 2.2 on 2019-05-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20190525_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Location',
            field=models.CharField(default='n', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='Subject_type',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
